export const themas = [
  { hoofd: "Techniek", sub: ["Frontaal", "Schuin-frontaal", "Zijwaarts", "Achterwaarts", "Aanname", "Handelingsnelheid", "Passing", "Leiden", "Dribbelen"] },
  { hoofd: "Speelwijze", sub: ["TT+ (TT- => TT+)", "TT- (TT+ => TT-)"] },
  { hoofd: "Fysiek", sub: ["Mobiliteit", "Stabiliteit", "Flexibiliteit"] },
  { hoofd: "Stilstaande fases", sub: ["Vrije trappen (B+, B-)", "Penalty's", "Corners (B+, B-)"] },
];

export const subthemas = [
  {
    hoofd: "Speelwijze",
    subs: [
      { name: "TT+ (TT- => TT+)", $isDisabled: true },
      { name: "Opbouwen", plus: true },
      { name: "Infiltraties naar de waarheidzone", plus: true },
      { name: "Beheersen van de waarheidzone", plus: true },
      { name: "Restverdediging", plus: true },
      { name: "Omschakeling B- naar B+", plus: true },
      { name: "TT- (TT+ => TT-)", $isDisabled: true },
      { name: "Opbouw verstoren", plus: false },
      { name: "Blokvorming", plus: false },
      { name: "Beheersen defensieve waarheidzone", plus: false },
      { name: "Beheersen van infiltraties naar defensieve waarheidzone", plus: false },
      { name: "Omschakeling B+ naar B-", plus: false },
    ],
  },
  {
    hoofd: "Fysiek",
    subs: [
      { name: "Uithouding", $isDisabled: true },
      { name: "EDT" },
      { name: "IDT" },
      { name: "EIT" },
      { name: "IIT" },
      { name: "Snelheid", $isDisabled: true },
      { name: "HKSV" },
      { name: "SS" },
      { name: "VV" },
      { name: "SUV" },
    ],
  },
];

export const intensiteit = [
  "Arbeid",
  "Rust",
  "Herhalingen",
  "Sessie",
  "Rustsessie",
];

export const onderdelen = [
  "Opwarming",
  "Techniekvorm",
  "Pasvorm",
  "Afwerkvorm",
  "Balbezitvorm / positiespel",
  "Wedstrijdvorm",
  "Spelvorm",
  "Cooling down",
  "Afgeleide wedstrijdvorm",
  "Keepertraining",
];

export const diplomas = [
  "Geen diploma",
  "Keepertrainer 1",
  "Keepertrainer 2",
  "Physical coach 1",
  "Physical coach 2",
  "Initiator C",
  "Instructeur B",
  "UEFA B",
  "UEFA A",
  "UEFA Pro",
];

export const basics = {
  plus: [
    { name: "B+", $isDisabled: true },
    { name: "Leiden en dribbelen" },
    { name: "Korte passing" },
    { name: "Controle op lage bal" },
    { name: "Doelpoging tot 10m (dichtbij)" },
    { name: "Doelpoging op lage voorzet" },
    { name: "Vrij en ingedraaid staan" },
    { name: "Vrijlopen: aanspeelbaar zijn door vrije ruimte te zoeken" },
    { name: "Inworp" },
    { name: "Halflange passing" },
    { name: "Controle op halfhoge" },
    { name: "Baldoelpoging vanop 15 à 20m (halfver)" },
    { name: "Doelpoging op halfhoge voorzet" },
    { name: "Vrijlopen om zelf anspeelbaar te zijn" },
    { name: "Steunen" },
    { name: "Corner + indirecte vrije trap" },
    { name: "Lange passing" },
    { name: "Controle op hoge bal" },
    { name: "Doelpoging vanaf 20m (ver)" },
    { name: "Doelpoging op hoge voorzet" },
    { name: "Vrijlopen om een medespeler aanspeelbaar te maken" },
    { name: "Vrijlopen door diep in de vrije ruimte te lopen (buitenspel omzeilen)" },
    { name: "Directe vrije trap" },
  ],
  minus: [
    { name: "B-", $isDisabled: true },
    { name: "Druk zetten, duel of remmend wijken" },
    { name: "Opstelling tussen tegenspeler en doel" },
    { name: "Korte dekking op korte pass" },
    { name: "Interceptie of afweren van korte pass" },
    { name: "Korte dekking op halflange pass" },
    { name: "Interceptie of afweren halflange pass" },
    { name: "Corner + indirecte vrije trap" },
    { name: "Speelhoeken afsluiten" },
    { name: "Korte dekking op lange pass" },
    { name: "Interceptie of afweren van lange pass" },
    { name: "Onderlinge dekking" },
    { name: "Directe vrije trap" },
  ],
};

export const tactics = {
  plus: [
    "1)	Openen: Breed",
    "2)	Openen: Diep",
    "3) Driehoekspel",
    "3a. Aanspeelbaarheid",
    "3b. Aanspeelbaarheid met aandacht wisselende voor spelsituaties.",
    "4)	Ruimte creëren voor zichzelf en het benutten ervan",
    "5)	Ruimte creëren voor een medespeler en het benutten ervan 06b.Efficiënte balcirculatie Progressie nastreven zonder risico op balverlies",
    "6)	Efficiënte balcirculatie",
    "6a. Progressie nastreven. Richting: ruit 1 => ruit 2: passing 1stegraad",
    "6b. Progressie nastreven zonder risico op balverlies",
    "7)	Efficiënte balcirculatie",
    "7a. Nauwkeurig doorspelen van de bal",
    "7b. Zo snel mogelijk nauwkeurig",
    "8)	Efficiënte balcirculatie: Een zo hoog mogelijke balsnelheid nastreven",
    "9)	Diagonale passing",
    "9a. Na aanspeelbaarheid",
    "9b. In & out passing naar de zwakke zone van de tegenpartij",
    "10) Een lijn overslaan bij passing diep (pass 2de gr)",
    "11) Efficiënte infiltratie met bal op het juiste moment: bij ruimte",
    "12) Efficiënte infiltratie zonder bal na een pass: Give & Go",
    "13) Efficiënte infiltratie zonder bal op het juiste moment: bij ruimte",
    "14) Infiltratie met bal: leiden of dribbelen: Challenge",
    "15) Een doelkans creëren via een individuele actie",
    "16) Een voorzet trappen",
    "16a over de grond die bruikbaar is vóór doel",
    "16b in de lucht die bruikbaar is voor doel",
    "17) Een subtiele eindpass in de diepte trappen naar een speler die in de rug van de laatste lijn duikt",
    "18) Efficiënte bezetting voor doel",
    "18a. door twee of drie spelers",
    "18b. bij voorzet: 1ste–2de paal, 11m&16m",
    "19) Strikte dekking ontvluchten: snel bewegen",
    "20) Diepte induiken maar opgelet off-side",
    "21) Zo snel mogelijk afwerken bij een werkelijke doelkans",
    "22) De aanvallers lopen zich vrij net vóór balrecuperatie (loshaken)",
    "23) Balrecuperatie: 1ste actie is diepte -gericht",
    "24) Diep blijven spelen",
    "25) Spelers in het blok: enkelen infiltreren (SPRINT)",
  ],
  minus: [
    "1)	Sluiten",
    "1a. Speelruimtes beperken",
    "1b. Speelruimtes beperken: Blok 35m -35m",
    "2)	Evenredige onderlinge afstanden",
    "3)	HOOG BLOK: aanv. & mids bevinden zich tussen de middenlijn en strafschopgebied van de tegenstander",
    "4)	Centrale verdediger dichtst bij het duel bepaalt off-sidelijn",
    "5)	Positieve pressing op de baldrager",
    "6)	Negatieve pressing op de baldrager",
    "7)	Dekking door dichtste medespeler",
    "8)	Geen kruisbeweging met naburige speler",
    "9)	Het schuiven en kantelen van het blok",
    "10) Een meeschuivende doelman (hoge positie)",
    "11) Het duel nooit verliezen: zich nooit laten uitschakelen",
    "12) Het duel proberen te winnen bij 100% zekerheid",
    "13) De bal recupereren door interceptie",
    "14) Collectieve W- pressing bij kans op balrecuperatie",
    "15) Zich niet laten uitschakelen door een individuele actie in de waarheidszone",
    "16) Een voorzet beletten",
    "17) Een subtiele eindpass in de diepte beletten: Centrum sluiten",
    "18) Efficiënte bezetting voor doel bij voorzet",
    "18a. defensieve T-vorm (2+1)",
    "18b. defensieve T-vorm (3+1)",
    "19) Kortere dekking in de waarheidszone: Split-Vision",
    "20) Geen systematische off-side door stap te zetten",
    "21) Doelpoging afblokken",
    "22) Een hoge compacte T-vorm:restverdediging van minstens 3 sp. + K",
    "23) Onmiddellijk na balverlies druk zetten en dieptepass verhinderen",
    "24) T-vorm: tegenaanval afremmen",
    "25) Niet T-vorm: zo snel mogelijk terug in het blok komen (SPRINT)",
  ],
};